inactive-opacity = 0.9;
opacity-rule = [
    "95:class_g = 'Alacritty' && focused",
    "100:window_type = 'tooltip'",
    "100:window_type = 'dropdown_menu'",
    "100:window_type = 'popup_menu'",

];
blur-method = "dual_kawase";
blur-strength = 5
blur-background = true

backend = "glx"

vsync = false;
transparent-clipping = true
menu-opacity = 1.0
